version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1306
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    image: three-tier:latest
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-container
      DB_USER: root
      DB_PASSWORD: root1306
      DB_NAME: db1
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:

