apiVersion: v1
kind: Service
metadata:
  name: news-service
spec:
  selector:
    app: news-app
  type: LoadBalancer                     # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000